import { useState } from "react";
import { ArrowLeft, ArrowUpRight, Check, Clock3, LockKeyhole, X } from "lucide-react";
import { Link } from "wouter";
import { sampleAttendance } from "@/academy-data";
import { logoImage } from "@/academy-data";

export default function Attendance() {
  const [studentId, setStudentId] = useState("");
  const [searched, setSearched] = useState(false);
  const [error, setError] = useState("");
  const check = () => { if (studentId.trim().toUpperCase() === sampleAttendance.id) { setError(""); setSearched(true); } else { setSearched(false); setError("No student record found. Try the sample ID COBRA102."); } };
  return <div className="min-h-screen bg-[#0b0b0c] text-[#f5f2ed]">
    <header className="border-b border-white/10"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-3 text-xs font-bold uppercase tracking-[.16em] text-[#a09c9e] hover:text-white"><ArrowLeft size={16} /> Back to academy</Link><div className="flex items-center gap-3"><img src={logoImage} alt="The Cobra Karate Academy" className="h-12 w-12 object-contain" /><div className="hidden text-right sm:block"><div className="display text-xl font-bold tracking-[.08em]">THE COBRA</div><div className="text-[.48rem] font-bold tracking-[.28em] text-[#cf3b31]">STUDENT SERVICES</div></div></div></div></header>
    <main className="mx-auto max-w-6xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div><div className="section-kicker">Student services / 01</div><h1 className="section-title mt-5">Check your attendance.</h1><p className="mt-7 max-w-md text-sm leading-7 text-[#969294]">Enter the student ID given to you by the academy. Your attendance record is read-only and can only be updated by a coach.</p><div className="mt-10 flex items-center gap-3 text-[.65rem] font-bold uppercase tracking-[.16em] text-[#777477]"><LockKeyhole size={15} className="text-[#cf3b31]" /> Private student record</div></div><div className="border border-white/10 bg-[#141416] p-6 sm:p-9"><label className="text-[.66rem] font-bold uppercase tracking-[.18em] text-[#9a9697]">Student ID</label><div className="mt-3 flex gap-2 border-b border-white/25 pb-2 focus-within:border-[#cf3b31]"><input value={studentId} onChange={e => setStudentId(e.target.value)} onKeyDown={e => e.key === "Enter" && check()} placeholder="COBRA102" className="min-w-0 flex-1 bg-transparent font-mono text-xl uppercase outline-none placeholder:text-[#555256]" /><button onClick={check} className="btn-press inline-flex items-center gap-2 bg-[#cf3b31] px-4 py-3 text-[.66rem] font-bold uppercase tracking-[.14em] hover:bg-[#e14b40]">Check <ArrowUpRight size={14} /></button></div>{error && <p className="mt-4 text-xs text-[#e06b62]">{error}</p>}<div className="mt-5 text-[.62rem] uppercase tracking-[.16em] text-[#777477]">Demo ID: <span className="text-white">COBRA102</span></div></div></div>
      {searched && <section className="mt-16 border-t border-white/15 pt-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="section-kicker">Record / {sampleAttendance.id}</div><h2 className="display mt-3 text-4xl font-bold uppercase">{sampleAttendance.student}</h2><div className="mt-2 text-xs uppercase tracking-[.15em] text-[#817d80]">{sampleAttendance.belt} · read-only view</div></div><div className="text-left sm:text-right"><div className="display text-6xl font-bold text-[#cf3b31]">{sampleAttendance.attendance}%</div><div className="text-[.62rem] font-bold uppercase tracking-[.18em] text-[#817d80]">Attendance</div></div></div><div className="mt-10 grid gap-px border border-white/10 bg-white/10 sm:grid-cols-3"><div className="bg-[#141416] p-5"><div className="text-[.62rem] font-bold uppercase tracking-[.18em] text-[#777477]">Present days</div><div className="display mt-2 text-4xl font-bold">{sampleAttendance.present}</div></div><div className="bg-[#141416] p-5"><div className="text-[.62rem] font-bold uppercase tracking-[.18em] text-[#777477]">Absent days</div><div className="display mt-2 text-4xl font-bold">{sampleAttendance.absent}</div></div><div className="bg-[#141416] p-5"><div className="text-[.62rem] font-bold uppercase tracking-[.18em] text-[#777477]">Late days</div><div className="display mt-2 text-4xl font-bold">{sampleAttendance.late}</div></div></div><div className="mt-12 max-w-3xl"><div className="mb-4 flex items-center justify-between"><h3 className="display text-2xl font-bold uppercase">Attendance history</h3><span className="text-[.62rem] uppercase tracking-[.16em] text-[#777477]">Latest sessions</span></div><div className="border-t border-white/15">{sampleAttendance.history.map(item => <div key={item.date} className="flex items-center justify-between border-b border-white/10 py-5"><div className="flex items-center gap-4"><span className={`flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold ${item.status === "Present" ? "bg-[#16382c] text-[#70d6aa]" : item.status === "Absent" ? "bg-[#3c2020] text-[#e06b62]" : "bg-[#40371c] text-[#e8c768]"}`}>{item.mark}</span><span className="text-sm font-bold">{item.date}</span></div><span className="flex items-center gap-2 text-xs uppercase tracking-[.14em] text-[#969294]">{item.status === "Present" ? <Check size={14} /> : item.status === "Absent" ? <X size={14} /> : <Clock3 size={14} />}{item.status}</span></div>)}</div></div></section>}
    </main>
  </div>;
}
